[package]
name = "vrc"
description = "The Velosiraptor Compiler"
license = "MIT"
version = "0.1.0"
authors = ["Reto Achermann <achreto@cs.ubc.ca>"]
edition = "2018"
readme = "README.md"


[dependencies]
# the argument parser
clap = "2.33.3"

# logging and errors
log = { version = "0.4.14", features = ["max_level_trace", "release_max_level_warn"] }
simplelog = "^0.10.0"
custom_error = "1.9.2"

# the parser combinators
[dependencies.nom]
version = "6"
