// Velosiraptor Compiler
//
//
// MIT License
//
// Copyright (c) 2022 The University of British Columbia, Vancouver, BC, Canada
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

//! # The FastModels Platform Generator: Interface
//!
//! This module generates the state description of the Arm FastModels implementation
//! of the translation unit.

// the path buffer
use std::path::Path;

// other libraries
use crustal as C;
use custom_error::custom_error;

// the defined errors
use crate::ast::Interface;
use crate::hwgen::fastmodels::state::to_state_class_name;
use crate::hwgen::HWGenError;

pub fn to_interface_class_name(name: &str) -> String {
    format!("{}{}Interface", name[0..1].to_uppercase(), &name[1..])
}

pub fn to_register_class_name(name: &str) -> String {
    format!("{}{}Register", name[0..1].to_uppercase(), &name[1..])
}

pub fn generate_interface_header(
    name: &str,
    state: &Interface,
    outdir: &Path,
) -> Result<(), HWGenError> {
    let mut scope = C::Scope::new();
    scope.set_filename("include/interface.hpp");

    let ifn = to_interface_class_name(name);
    let scn = to_state_class_name(name);

    scope.push_doc_str(format!("The Interface of the '{}' Translation Unit\n\n", scn).as_str());
    scope.push_doc_str("WARNING: This file is auto-generated by the  Velosiraptor compiler.\n");

    // set the header guard
    let guard = scope.new_ifdef(format!("{}_INTERFACE_HPP_", name.to_uppercase()).as_str());

    // create the scope guard
    let s = guard.guard().then_scope();

    s.new_comment("system includes");
    s.new_include("stddef.h", true);
    s.new_include("assert.h", true);

    s.new_comment("framework includes");
    s.new_include("generic/types.hpp", true);
    s.new_include("generic/interface_base.hpp", true);

    s.new_comment("translation unit specific includes");
    s.new_include("state.hpp", true);

    // TODO: make this dependent on the interface type
    s.new_include("registers.hpp", true);

    // create a new class in the scope
    let c = s.new_class(ifn.as_str());

    c.set_base("InterfaceBase", C::Visibility::Public);

    let state_ptr_type = C::Type::from_ptr(&C::Type::new_class(&scn));

    let cons = c.new_constructor();
    cons.new_argument("state", state_ptr_type.clone());

    // add the state attribute
    c.new_attribute("_state", state_ptr_type);

    for f in state.fields() {
        let rcn = to_register_class_name(&f.field.name);
        let fieldname = format!("_{}", &f.field.name);
        let ty = C::Type::new_class(&rcn);
        c.new_attribute(&fieldname, ty);
    }

    // save the scope
    scope.to_file(outdir, true)?;

    Ok(())
}

pub fn generate_interface_impl(
    name: &str,
    state: &Interface,
    outdir: &Path,
) -> Result<(), HWGenError> {
    let mut scope = C::Scope::new();

    let ifn = to_interface_class_name(name);
    let scn = to_state_class_name(name);

    scope.set_filename("interface.cpp");

    scope.push_doc_str(format!("The Interface of the '{}' Translation Unit\n\n", scn).as_str());
    scope.push_doc_str("WARNING: This file is auto-generated by the  Velosiraptor compiler.\n");

    scope.new_comment("fastmodels includes");
    scope.new_include("pv/RemapRequest.h", true);

    scope.new_comment("framework includes");
    scope.new_include("generic/logging.hpp", true);

    scope.new_comment("unit includes");
    scope.new_include("registers.hpp", true);
    scope.new_include("interface.hpp", true);

    let c = scope.new_class(ifn.as_str());

    let state_ptr_type = C::Type::from_ptr(&C::Type::new_class(&scn));

    let cons = c.new_constructor();

    let m = cons.new_argument("state", state_ptr_type);

    let pa = C::Expr::from_method_param(m);

    cons.push_parent_initializer(C::Expr::fn_call("InterfaceBase", vec![pa.clone()]));
    cons.push_initializer("_state", pa.clone());

    for f in state.fields() {
        let fieldname = format!("_{}", f.field.name);
        let rcn = to_register_class_name(&f.field.name);
        cons.push_initializer(fieldname.as_str(), C::Expr::fn_call(&rcn, vec![pa.clone()]));

        let this = C::Expr::this();
        let field = C::Expr::field_access(&this, &fieldname);
        cons.push_stmt(C::Stmt::fn_call(C::Expr::method_call(
            &this,
            "add_register",
            vec![C::Expr::addr_of(&field)],
        )));
    }

    scope.to_file(outdir, false)?;

    Ok(())
}
