on:
  push:
    branches:
      - main
  pull_request:

name: Unit Tests
jobs:
  compile_and_test:
    name: "libvelosisynth"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: libvelosisynth_clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # can add a `-- --deny warnings` here to convert warnings into errors
          args:
      - name: libvelosisynth_build
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./lib/velosisynth/Cargo.toml
