on:
  push:
    branches:
      - main
  pull_request:

name: Unit Tests
jobs:
  compile_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: True
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
      - name: libvelosisynth
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --manifest-path ./lib/velosisynth/Cargo.toml
