on:
  push:
    branches:
      - main
  pull_request:

name: Unit Tests
jobs:
  compile_and_test:
    runs-on: ubuntu-latest
    name: "libvelosiast"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: libvelosias_clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # can add a `-- --deny warnings` here to convert warnings into errors
          args:  --workspace --manifest-path  ./lib/velosiast/Cargo.toml
      - name: libvelosiast_build
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --manifest-path ./lib/velosiast/Cargo.toml
